name: 'release-rs'
description: 'A robust GitHub Action for building and releasing Rust binaries across multiple platforms.'
author: 'xctions'

inputs:
  binary_name:
    description: 'The name of the binary to be built. Defaults to the repository name.'
    required: false
  release-tag:
    description: 'The git tag for the release.'
    required: true
  platforms:
    description: 'A comma-separated list of platforms to build for.'
    required: false
    default: 'linux-x86_64,windows-x86_64'
  github-token:
    description: 'The GitHub token for creating releases and uploading assets.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine Binary Name
      id: get_binary_name
      shell: bash
      run: |
        if [[ -n "${{ inputs.binary_name }}" ]]; then
          echo "binary_name=${{ inputs.binary_name }}" >> $GITHUB_OUTPUT
        else
          echo "binary_name=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
        fi

    - name: Run Secure Build
      shell: bash
      run: |
        # Note: For now, we are hardcoding a single platform for simplicity.
        # We will replace this with matrix logic in the next phase.
        ${{ github.action_path }}/scripts/secure-build.sh \
          ${{ steps.get_binary_name.outputs.binary_name }} \
          x86_64-unknown-linux-gnu
