name: 'release-rs'
description: 'A robust GitHub Action for building and releasing Rust binaries across multiple platforms.'
author: 'xctions'

inputs:
  binary_name:
    description: 'The name of the binary to be built. Defaults to the repository name.'
    required: false
  release-tag:
    description: 'The git tag for the release.'
    required: true
  platforms:
    description: 'A comma-separated list of platforms to build for.'
    required: false
    default: 'linux-x86_64,windows-x86_64'
  github-token:
    description: 'The GitHub token for creating releases and uploading assets.'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Debug Inputs"
      shell: bash
      run: |
        echo "Binary Name: ${{ inputs.binary_name }}"
        echo "Release Tag: ${{ inputs.release-tag }}"
        echo "Platforms: ${{ inputs.platforms }}"